### ISSUE TITLE
Conflicts with sensu-plugin version 1.1.0

### ISSUE THREAD

**Issue by demonccc** [SimpleFinance/check_disk#7]
Hi, 

This is the output of the the script `check_disk.rb` when the system has installed the gem sensu-plugin version 1.1.0:
```
Invalid check argument(s): invalid option: -p, ["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:55:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:55:in `block in <class:CLI>'"]
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate check_disk-0.1.3, because sensu-plugin-1.1.0 conflicts with sensu-plugin (>= 0.3.0, ~> 0.3) (Gem::LoadError)
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:117:in `rescue in require'
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in `require'
	from /etc/sensu/plugins/system/check_disk.rb:4:in `<main>'
```

I resolved this issue by adding this line to the script: 

``` gem 'sensu-plugin','=0.3.0' ```

Regards.

**Comment by miah** [comment]
We could also update the gemspec to work with the newer release of sensu-plugins. I'll have a PR shortly.
